# Generated by Django 4.1.6 on 2023-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=254)),
                ("LastName", models.CharField(max_length=254)),
                ("Email", models.CharField(max_length=254)),
            ],
        ),
    ]
